### PR TITLE
External topOffset and observe changes

### PR DESCRIPTION
**Pull request by iNono22**
#4 & #3

### CODE REVIEW

**Comment by MarioIannotta** [comment]
Hey Arnaud,
thanks for your contribute.

I think using a closure like `open var pullUpControllerDidScroll: ((_ topOffset: CGFloat) -> Void)?` instead of a delegate would make the code easier to read and more _swifty_.

Thank you, 
Mario.

**Comment by krezzoid** [comment]
@MarioIannotta maybe it will be better to have closure notifications such:
```
open var willMoveToStickyPoint: ((_ point: CGFloat) -> Void)?
open var didMoveToStickyPoint: ((_ point: CGFloat) -> Void)?

```
because you are initially operates with sticky points.
Calculated value for offset from the top already presented in self.view.frame.origin.y

take a look my pull request with these changes (https://github.com/MarioIannotta/PullUpController/pull/6).

**Comment by MarioIannotta** [comment]
Looks good, thank you 🍻

**Comment by MarioIannotta** [comment]
Should be closed with #6

**Pull request merged**
